### ISSUE TITLE
Questions regarding antidote.lite

### ISSUE THREAD

**Issue by rieje** [mattmc3/zsh_unplugged#15]
* In zsh_unplugged, symlink is used so it doesn't need to search for the init files again on every shell init. Does antitdote.lite not benefit from this (I don't see any symlinking)?

* I'm interested in antidote.lite--it seems to have all the essential functions and I don't use much plugins. I came across a comment that the antidote is actually supposed to be faster despite being more featureful--if that's the case it's surprising and I'm curious how antidote.lite can have matching performance considering there's less logic and code involved. At a glance it looks stuff is done async already.

* `plugin-load` (and I assume equivalents by other plugin managers) assumes zsh plugins follow some kind of naming/coding standard, right? I'm thinking of not using a plugin-load function--such functions probably sources more files than needed (even if it doesn't hurt?). Correct me if I'm wrong but sourcing only the the files suggested by plugin developers seems (slightly) less prone to errors and would also mean there's no need for symlinking.

* I'm not really sure what's the difference between `ANTIDOTE_LITE_HOME` and `ZPLUGINDIR` (only the former has contents after a clone. Is it trivial to have file structure e.g. `$ANTIDOTE_LITE_HOME/powerlevel10k___romkatv` to eliminate an extra nested directory over the current $ANTIDOTE_LITE_HOME/romkatv/powerlevel10k)? I was looking into [the code](https://github.com/mattmc3/zsh_unplugged/blob/main/antidote.lite.zsh#L21-L24) and trying to see if I can achieve that but found it doesn't seem to anything, i.e. replacing that loop with the following yielded the same results:

    for repo in "$@"; do
      [[ -e $ANTIDOTE_LITE_HOME/$repo ]] || repos+=$repo
    done

Much appreciated.

**Comment by mattmc3** [comment]
> In zsh_unplugged, symlink is used so it doesn't need to search for the init files again on every shell init. Does antitdote.lite not benefit from this (I don't see any symlinking)?

No, antidote.lite works more like antidote (hence the name). If you want, you can even get the same speed as antidote by creating a static file that you only regenerate when it changes:

```zsh
# Set the root name of the plugin files (.txt and .zsh).
zsh_plugins=${ZDOTDIR:-$HOME}/.zsh_plugins

# Ensure a .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# Generate a new static file whenever .zsh_plugins.txt is updated.
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  source /path/to/antidote.lite.zsh
  plugins=("${(@f)$(<${zsh_plugins}.txt)}")    # read plugins file
  plugins=(${plugins:#\#*})                    # strip comments
  plugin-clone $plugins                        # clone missing plugins
  plugin-script $plugins >|${zsh_plugins}.zsh  # generate a static file
fi

# Source your static plugins file.
source ${zsh_plugins}.zsh
```

> antidote is actually supposed to be faster despite being more featureful... At a glance it looks stuff is done async already.

Antidote has all sorts of extra features and optimizations like caching and zcompiling. To do that requires more code - so more code doesn't always mean slower. That said, if you use the technique above you basically get the same performance at the end of the day. But with antidote.lite it's code you have to write, understand, and maintain. With antidote, all that code is stuff I maintain for you.

> plugin-load (and I assume equivalents by other plugin managers) assumes zsh plugins follow some kind of naming/coding standard, right?

There's [a de-facto plugin standard started by Oh-My-Zsh](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#adding-a-new-plugin), which defines that Zsh plugin files should be named foo.plugin.zsh. Often times those files are shells that source other files, but that's the standard. There's been [other attempts at extending it](https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html) as well. While it's true you could skip a step, you'd have to code that for every plugin rather than just using the standard file. rupa/z uses z.sh for example.

> I'm not really sure what's the difference between ANTIDOTE_LITE_HOME and ZPLUGINDIR

ZPLUGINDIR is for compatibility with the original zsh_unplugged, and is where you can put your local (non-git hosted) plugins, similar to OMZ's ZSH_CUSTOM.

Hope this helps.
