### ISSUE TITLE
Clarity on Oh-My-Zsh Plugins

### ISSUE THREAD

**Issue by RLovelett** [mattmc3/zsh_unplugged#8]
First of all, this has been a wonderful project for me. Really has extended my knowledge of what is going on under the hood of my shell.

I am trying to port my existing manager (antigen) over to this concept and I am struggling with how I would get my 1 or 2 Oh-My-Zsh plugins in here. For instance, the [git](https://github.com/ohmyzsh/ohmyzsh/tree/ef3f7c43a91eb2c90098843b0ee9193bb52cdc96/plugins/git) plugin.

I tried following [the section on Oh-my-Zsh](https://github.com/mattmc3/zsh_unplugged#oh-my-zsh) but honestly, I am not sure what `$ZSH_CUSTOM` is.

I ended up coming up with this:

```zsh
function oh-my-zsh-plugin-load() {
  local repo ohmyzsh_dir plugin_name plugin_dir initfile initfiles
  ZPLUGINDIR=${ZPLUGINDIR:-${ZDOTDIR:-$HOME/.config/zsh}/plugins}
  for repo in $@; do
    ohmyzsh_dir=$ZPLUGINDIR/ohmyzsh
    plugin_name=${repo:t}
    plugin_dir=$ohmyzsh_dir/plugins/$plugin_name
    initfile=$plugin_dir/$plugin_name.plugin.zsh
    if [[ ! -d $ohmyzsh_dir ]]; then
      echo "Cloning Oh-My-Zsh"
      git clone -q --depth 1 --recursive --shallow-submodules https://github.com/ohmyzsh/ohmyzsh.git $ohmyzsh_dir
    fi
    if [[ ! -e $initfile ]]; then
      initfiles=($plugin_dir/*.plugin.{z,}sh(N) $plugin_dir/*.{z,}sh{-theme,}(N))
      [[ ${#initfiles[@]} -gt 0 ]] || { echo >&2 "Plugin has no init file '$repo'." && continue }
      ln -sf "${initfiles[1]}" "$initfile"
    fi
    fpath+=$plugin_dir
    (( $+functions[zsh-defer] )) && zsh-defer . $initfile || . $initfile
  done
}

# List of the Oh-My-Zsh plugins
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins
ohmyzsh_plugins=(
  git
)

oh-my-zsh-plugin-load $ohmyzsh_plugins
```

Does this seem reasonable to you? Or was this already provided by your guide and I just misunderstood it?

**Comment by mattmc3** [comment]
@RLovelett - thank you for the kind words. I'm happy to help.

I probably didn't give enough attention to the OMZ section, so let me clarify a couple things and then get to your questions.

There's a chicken and egg (🐔 & 🥚 ) problem when it comes to how we talk about frameworks like Oh-My-Zsh. Basically, do we:
1. fully commit to using Oh-My-Zsh and let it manage your config and load all your plugins. In other words, we drive everything from OMZ?
-OR-
2. treat Oh-My-Zsh like it's just a plugin itself and drive everything from a plugin manager?

What the README currently shows is how you handle the first scenario - namely, that you use Oh-My-Zsh as intended, but want to add a few custom 3rd party plugins to it from outside sources. The OMZ project deals with that here, and reading that would answer your questions about ZSH_CUSTOM: https://github.com/ohmyzsh/ohmyzsh/wiki/Customization

Now, that said, what I think you have in your code snippet is the second scenario - treating Oh-My-Zsh itself like a plugin, and then loading parts of that. Atigen, Antibody, Zgen, and Zgenom are all capable of doing some OMZ magic. We can easily do that too without any modifications to our plugin-load function! BUT - we just can't call our list of plugins 'plugins', because Oh-My-Zsh does some magic behind the scenes with that variable. OMZ's internals have a lot of hidden dependencies on being loaded the intended way, and not by a plugin manager. Still, we can do this.

Here's the code you want:

```
# this is the original, unchanged plugin-load function - we need no modifications here
# clone a plugin, identify its init file, source it, and add it to your fpath
function plugin-load() {
  local repo plugin_name plugin_dir initfile initfiles
  ZPLUGINDIR=${ZPLUGINDIR:-${ZDOTDIR:-$HOME/.config/zsh}/plugins}
  for repo in $@; do
    plugin_name=${repo:t}
    plugin_dir=$ZPLUGINDIR/$plugin_name
    initfile=$plugin_dir/$plugin_name.plugin.zsh
    if [[ ! -d $plugin_dir ]]; then
      echo "Cloning $repo"
      git clone -q --depth 1 --recursive --shallow-submodules https://github.com/$repo $plugin_dir
    fi
    if [[ ! -e $initfile ]]; then
      initfiles=($plugin_dir/*.plugin.{z,}sh(N) $plugin_dir/*.{z,}sh{-theme,}(N))
      [[ ${#initfiles[@]} -gt 0 ]] || { echo >&2 "Plugin has no init file '$repo'." && continue }
      ln -sf "${initfiles[1]}" "$initfile"
    fi
    fpath+=$plugin_dir
    (( $+functions[zsh-defer] )) && zsh-defer . $initfile || . $initfile
  done
}

# OMZ expects a list named plugins
# it can only contain the names of actual OMZ plugins
plugins=(
  git
  copydir
  extract
  magic-enter
)

# since we're using OMZ, we can even use one of its themes
ZSH_THEME=avit

# NOW, here's the trick - let's use the name 'repos' for our plugin-load function instead of 'plugins'.
# that will let OMZ exist with our 3rd party plugins
repos=(
  ohmyzsh/ohmyzsh
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-history-substring-search
  zdharma-continuum/fast-syntax-highlighting
)
plugin-load $repos
```

Hope this helps!

**Comment by RLovelett** [comment]
This is so much simpler than my approach. The fact that OMH was already using `plugin` variable to load plugins, well we can add that to the list of things I learned.

Again thank you.
